src/java/models/Account_Role.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

/**
 *
 * @author Nitro
 */
public class Account_Role {

    private int Id;
    private String Role;

    public Account_Role() {
    }

    public Account_Role(int Id, String Role) {
        this.Id = Id;
        this.Role = Role;
    }

    public int getId() {
        return Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    public String getRole() {
        return Role;
    }

    public void setRole(String Role) {
        this.Role = Role;
    }

    @Override
    public String toString() {
        return "Account_Role{" + "Id=" + Id + ", Role=" + Role + '}';
    }
}

src/java/controller/HomeServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dao.DAOBrand;
import dao.DAOCategory;
import dao.DAOProduct;
import dao.DAOSize;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import models.Brand;
import models.Cart;
import models.Category;
import models.Item;
import models.Products;
import models.Size;
import jakarta.servlet.http.Cookie;

/**
 *
 * @author Nitro
 */
public class HomeServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try {
            DAOProduct dao = new DAOProduct();
            DAOCategory dc = new DAOCategory();
            DAOBrand db = new DAOBrand();
            List<Category> listC = dc.getAllCategory();
            List<Category> listC2 = dc.getAllCategory2();
            DAOSize ds = new DAOSize();
            DAOProduct dp = new DAOProduct();
            List<Products> list2 = dp.getAllProducts();
            List<Size> list1 = ds.getAllSize();

            Cookie[] arr = request.getCookies();
            String txt = "";
            if (arr != null) {
                for (Cookie cookie : arr) {
                    if (cookie.getName().equals("cart")) {
                        txt += cookie.getValue();
                    }
                }
            }
            Cart cart = new Cart(txt, list2, list1);
            List<Item> listItem = cart.getItems();
            int n;
            if (listItem != null) {
                n = listItem.size();
            } else {
                n = 0;
            }
            request.setAttribute("size", n);
            List<Brand> listB = db.getAllBrand();
            request.setAttribute("listC", listC);
            request.setAttribute("listC2", listC2);

            request.setAttribute("listB", listB);
            request.getRequestDispatcher("/view/userAccess/home.jsp").forward(request, response);
        } catch (Exception e) {
            request.getRequestDispatcher("/view/common/error.jsp").forward(request, response);
        }

    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/LoginServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dao.DAOAccount;
import dao.DAOBrand;
import dao.DAOCategory;
import dao.DAOProduct;
import dao.DAOSize;
import utils.PasswordHashing;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import models.Account;
import models.Brand;
import models.Cart;
import models.Category;
import models.Item;
import models.Products;
import models.Size;
import java.util.List;
import utils.SenMail;

/**
 *
 * @author Nitro
 */
public class LoginServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet Controller_Login</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet Controller_Login at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try {
            DAOSize ds = new DAOSize();
            DAOProduct dp = new DAOProduct();
            DAOBrand db = new DAOBrand();
            DAOCategory dc = new DAOCategory();
            List<Category> listC = dc.getAllCategory();
            List<Category> listC2 = dc.getAllCategory2();
            List<Brand> listB = db.getAllBrand();
            List<Products> list2 = dp.getAllProducts();
            List<Size> list1 = ds.getAllSize();

            Cookie[] arr = request.getCookies();
            String txt = "";
            if (arr != null) {
                for (Cookie cookie : arr) {
                    if (cookie.getName().equals("cart")) {
                        txt += cookie.getValue();
                    }
                }
            }
            Cart cart = new Cart(txt, list2, list1);
            List<Item> listItem = cart.getItems();
            int n;
            if (listItem != null) {
                n = listItem.size();
            } else {
                n = 0;
            }
            request.setAttribute("listC", listC);
            request.setAttribute("listC2", listC2);
            request.setAttribute("listB", listB);
            request.setAttribute("size", n);
            request.getRequestDispatcher("/view/userAccess/login.jsp").forward(request, response);
        } catch (Exception e) {
            request.getRequestDispatcher("/view/common/error.jsp").forward(request, response);
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String email = request.getParameter("email");
        String password = request.getParameter("password");
        password = PasswordHashing.toSHA1(password);
        DAOAccount da = new DAOAccount();
        Account a = da.getAccount(email, password);

        if (a != null) {
            if (a.getRoleID() == 5) {
                HttpSession session = request.getSession();
                session.setAttribute("acc", a);
                session.setAttribute("shipperID", a.getShipper().getShipperID()); // Lưu shipperID vào session
                response.sendRedirect("/SWP391_OnlineShopping/shipper/ShipperReceiveOrder");
            } else if (a.getStatus() == 2) {
                Account a1 = da.getAccountById(da.getIdByEmail(email));
                SenMail sm = new SenMail();
                String code = sm.getRandom();
                boolean test = sm.sendEmail(a1, code);
                if (test) {
                    HttpSession session = request.getSession();
                    session.setAttribute("code", code);
                    session.setAttribute("acc", a1);
                    response.sendRedirect("/SWP391_OnlineShopping/account/signupverify");
                } else {
                    // Nếu gửi email xác thực không thành công, có thể thông báo lỗi cho người dùng tại đây
                }
            } else if (a.getStatus() == 3) {
                request.getRequestDispatcher("/view/common/band.jsp").forward(request, response);;

            } else if (a.getRoleID() == 1) {
                HttpSession session = request.getSession();
                session.setAttribute("acc", a);
                response.sendRedirect("/SWP391_OnlineShopping/administrator/homeAdmin");

            } else if (a.getRoleID() == 2) {
                HttpSession session = request.getSession();
                session.setAttribute("acc", a);
                response.sendRedirect("/SWP391_OnlineShopping/manager/dashboard-manager");
            } else {
                Cookie cookie = new Cookie("email", email);
                cookie.setMaxAge(600);
                response.addCookie(cookie);
                HttpSession session = request.getSession();
                session.setAttribute("acc", a);
                response.sendRedirect("/SWP391_OnlineShopping/home");
            }

        } else {
            request.setAttribute("text", "Sai tài khoản hoặc mật khẩu !");
            request.getRequestDispatcher("/view/userAccess/login.jsp").forward(request, response);
        }

    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/NewPasswordServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dao.DAOAccount;
import utils.PasswordHashing;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 *
 * @author Nitro
 */
public class NewPasswordServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet Controller_NewPassword</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet Controller_NewPassword at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("/view/userAccess/new-password.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try {
            String email = request.getParameter("email");
            String newpassword = request.getParameter("newpassword");
            String confirm = request.getParameter("confirm");
            if (newpassword.length() <= 4) {
                request.setAttribute("text", "Mật khẩu phải lớn hơn 4 kí tự");
                request.getRequestDispatcher("/view/userAccess/new-password.jsp").forward(request, response);
            } else if (!newpassword.equals(confirm)) {
                // Nếu mật khẩu mới và mật khẩu xác nhận không khớp, hiển thị thông báo lỗi
                request.setAttribute("text", "Mật khẩu mới không trùng khớp");
                request.getRequestDispatcher("/view/userAccess/new-password.jsp").forward(request, response);
            } else {
                DAOAccount dao = new DAOAccount();
                dao.changeNewPass(newpassword, email);
                response.sendRedirect("/SWP391_OnlineShopping/home");
            }
        } catch (Exception e) {
            request.getRequestDispatcher("/view/common/error.jsp").forward(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/view/userAccess/change-password.jsp
<%-- 
    Document   : edit-profile
    Created on : Sep 21, 2023, 9:18:56 AM
    Author     : Nitro
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Change password</title>
        <link href="/SWP391_OnlineShopping/assets/img/img-01.png" rel="icon">

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="/SWP391_OnlineShopping/assets/css/edit-profile.css" rel="stylesheet">
        <link href="/SWP391_OnlineShopping/assets/css/style.css" rel="stylesheet">
        <style>
            body {
                background-image: url("/SWP391_OnlineShopping/assets/img/baicat.jpeg");
                background-size: cover;
            }
        </style>
        <script type="text/javascript">
            window.onpageshow = function (event) {
                if (event.persisted) {
                    location.reload(); // Tải lại trang khi người dùng quay lại từ lịch sử
                }
            };
        </script>
    </head>
    <body>


        <div class="container">
            <div class="main-body">
                <c:set value="${requestScope.data}" var="i"/>
                <div>
                    <div class="card-body">
                        <h5 style=""><a href="/SWP391_OnlineShopping/account/profile"> <img src="/SWP391_OnlineShopping/assets/img/back.png" height="30px" width="30px" alt="alt"/>Back</a>
                        </h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <form action="change-password" method="post">
                            <div class="card">
                                <jsp:include page="/view/common/menuprofile.jsp"></jsp:include>
                                    <div class="card-body">
                                        <div class="row mb-3">
                                            <div class="col-sm-3">
                                                <h6 class="mb-0">Email</h6>
                                            </div>
                                            <div class="col-sm-9 text-secondary">
                                                <input name="email"type="text" class="form-control" value="${sessionScope.acc.email}" readonly>
                                            <input type="hidden" name="id" value="${sessionScope.acc.id}"/>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Old Password </h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input name="oldpassword" type="text" class="form-control" placeholder="Old Password"required>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">New Password
                                            </h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input type="text" class="form-control" name="newpassword"  placeholder="New Password"required>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Confirm</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input name="confirm" type="text" class="form-control" placeholder="Confirm Password" required>
                                        </div>
                                    </div>

                                    <div style=" color: #a94442;
                                         padding: 10px;
                                         border-radius: 5px;">
                                        <strong>${requestScope.text}</strong>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-3"></div>
                                        <div class="col-sm-9 text-secondary">
                                            <input type="submit" class="btn btn-primary px-4" value="Save Changes">
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

web/view/userAccess/profile.jsp
<%-- 
    Document   : profile
    Created on : Sep 21, 2023, 8:11:29 AM
    Author     : Nitro
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <title>Profile</title>

    <head>
        <link href="/SWP391_OnlineShopping/assets/img/img-01.png" rel="icon">

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="/SWP391_OnlineShopping/assets/css/userprofile.css" rel="stylesheet"> 
        <link href="/SWP391_OnlineShopping/assets/css/style.css" rel="stylesheet">
        <link href="/SWP391_OnlineShopping/assets/css_admin/style.css" rel="stylesheet">
        <script type="text/javascript">
            window.onpageshow = function (event) {
                if (event.persisted) {
                    location.reload(); // Tải lại trang khi người dùng quay lại từ lịch sử
                }
            };
        </script>
    </head>

    <!------ Include the above in your HEAD tag ---------->

    <body>


        <div class="container emp-profile">
            <jsp:include page="/view/common/menuprofile.jsp"></jsp:include>

            <c:set value="${requestScope.data}" var="i"/>

            <div class="row">
                <div class="col-md-4">
                    <div class="profile-img">
                        <form action="profile" method="post">
                            <div>
                                <div class="form-group">
                                    <input value="${i.id}" name="accountid" type="hidden" class="form-control" >
                                </div>
                                <div class="form-group col-md-12">
                                    <img style="width: 150px; height: 180px" src="/SWP391_OnlineShopping/assets/avatar/${i.profile_picture}" alt="">
                                    <input name="image" type="file">
                                </div>
                            </div>
                            <div class="modal-footer" style="margin-bottom: 30px;">
                                <input type="submit" style="cursor: pointer" class="btn btn-success" value="Change Image">
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="profile-head">
                        <h5>
                            INFOMATION USER
                        </h5>
                        <h6>
                            ${i.email}
                        </h6>
                        <p class="proile-rating">DATE_AT : <span>${i.create_at}</span></p>
                        <p class="proile-rating">Role : <span>${i.role}</span></p>

                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <a href="edit-profile" class="profile-edit-btn">Edit Profile  </a>
                    <a></a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="profile-work">
                        <p>Setting</p>
                        <h2><a href="change-password">Change Password</a><br/></h2>

                    </div>
                </div>
                <div class="col-md-8">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Email</label>
                                </div>
                                <div class="col-md-6">
                                    <p>${i.email}</p>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-6">
                                    <label>FullName</label>
                                </div>
                                <div class="col-md-6">
                                    <p>${i.fullname}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Gender</label>
                                </div>
                                <div class="col-md-6">
                                    <p>
                                        ${i.gender ? 'Nam' : 'Nữ'}
                                    </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <label>Phone</label>
                                </div>
                                <div class="col-md-6">
                                    <p>${i.phone_number}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>Address</label>
                                </div>
                                <div class="col-md-6">
                                    <p>${i.address}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <% String successMessage = (String) request.getSession().getAttribute("successMessage"); %>
            <% if (successMessage != null) { %>
            <div class="alert alert-success" id="success-message">
                <strong><%= successMessage %></strong>
            </div>  
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var successMessage = document.getElementById('success-message');
                    successMessage.style.position = 'fixed';
                    successMessage.style.top = '100px';
                    successMessage.style.right = '10px';
                    successMessage.style.display = 'block';
                    setTimeout(function () {
                        successMessage.style.display = 'none';
                    }, 4000);
                });
            </script>
            <% } %>

            <% request.getSession().removeAttribute("successMessage"); %>
        </div>

    </body>


</html>